apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-service-a-to-service-b
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: service-a  # This applies to Service A
  policyTypes:
  - Egress
  egress:
  - to:
      - podSelector:  # Select Service B by its pod label
          matchLabels:
            app: service-b
    ports:
    - protocol: TCP
      port: 80  # Block access to port 80 of Service B